### ISSUE TITLE
c14 with cron ?

### ISSUE THREAD

**Issue by chico200987** [online-net/c14-cli#17] opened 2017-01-17 23:25 UTC
I have some problem with a really simple script, executed by cron.

Here is it, for testing : 

`
#! /bin/bash
c14 upload /tmp/2017-01-17-backup.tar.gz xxxx-xxxxx-xxxxx
`

I was logged as root and I setup this script using crontab -e. 

On executing this script manually, everything is working fine, but when cron did it, i have this error on my mail : 

>  FATAL[0000] You need to specified a name

Can you help me to solve this problem please ?

Thanks

Regards

**Comment by coolya** [comment] 2017-01-26 21:40
I think the problem is that when stdin is not a terminal the upload command always assumes that its in piped mode. Which is the case when its executed by cron.

https://github.com/online-net/c14-cli/blob/master/pkg/commands/upload.go#L54

**Comment by otzy007** [comment] 2017-02-06 19:04
Hi,

Did you find a fix for this issue?
I'm getting the same error when trying to run c14 into a cronjob

**Comment by chico200987** [comment] 2017-02-06 20:32
@coolya Thanks for your answer. Do you have any idea of how we have to modify this line to work with cron ?

@otzy007 : Unfortunately, i didn't find any issue yet :(

**Comment by coolya** [comment] 2017-02-06 20:35
@chico200987 I'm working on fix and will sent a pull request during this week.

**Comment by chico200987** [comment] 2017-02-06 20:38
@coolya Greet thannnnnks !

**Comment by coolya** [comment] 2017-02-10 20:40
@chico200987 @otzy007 should work now.

**Comment by chico200987** [comment] 2017-02-10 21:27
It's perfect, thanks again !

**Comment by Solvik** [comment] 2017-03-07 10:24
Thanks to @coolya it's fixed, I'm closing the issue

**Closed by Solvik** 2017-03-07 10:24 UTC
